SHF-374
shuffle-app/shuffle_uikit pull request #200
Opened 2023-08-30 14:26 UTC by rel1nce

Реализация основного функционала кнопки согласно техническому заданию. Добавление нескольких видов анимаций, вибраций и поведения.

2023-08-30 16:14 UTC, romancores requested changes
в целом ок все, маленькие вещи можно улучшить

2023-08-30 19:18 UTC, romancores requested changes

2023-08-30 19:18 UTC, romancores commented on lib/ui_kit/organisms/animated_buttons/fingerprint_button.dart
> +    _controller.removeStatusListener((status) {
вынеси функцию статус лисенера в отдельное объявление, зачем еще 10 строк добавлять коду лишних

2023-08-30 21:13 UTC, romancores approved these changes

2023-08-31 07:08 UTC, naveenpardeep approved these changes

2023-08-31 12:31 UTC, merged