SHF-396
shuffle-app/shuffle_uikit pull request #224
Opened 2023-09-11 10:39 UTC by rel1nce

Интеграция светлой темы, UiKitColorScheme и рефактор большинства виджетов для работы с двумя темами.

2023-09-11 13:28 UTC, romancores requested changes

2023-09-11 13:28 UTC, romancores commented on lib/ui_kit/atoms/buttons/blurred_progress_button.dart
почему тут не inversePrimary?

2023-09-11 13:28 UTC, romancores commented on lib/ui_kit/atoms/buttons/ordinary_text_button.dart
> +            style: TextStyle(
тут если я правильно помню задается цвет из темы, поэтому следует убрать назначения стиля тексту

2023-09-11 13:28 UTC, romancores commented on lib/ui_kit/atoms/buttons/outlined_text_button.dart
> +          color: context.uiKitTheme!.colorScheme.inversePrimary,
куда делись замещения цвета borderColor и неактивного состояния с ColorsFoundation.darkNeutral500

2023-09-11 13:28 UTC, romancores commented on lib/ui_kit/atoms/inputs/ui_kit_input_field_no_icon.dart
> +                color: Colors.white,
почему тут не поставлен inversePrimary?

2023-09-11 13:28 UTC, romancores commented on lib/ui_kit/molecules/chips/ui_kit_bordered_chip_with_icon.dart
> +      color: isSelected ? colorScheme?.primary : colorScheme?.inversePrimary,
разве не наоборот должно быть?

2023-09-11 13:28 UTC, romancores commented on lib/ui_kit/molecules/chips/ui_kit_bordered_chip_with_icon.dart
> +                  color: isSelected ? colorScheme?.inversePrimary : colorScheme?.primary,
тоже вопрос как выше

2023-09-11 14:23 UTC, rel1nce commented on lib/ui_kit/molecules/place/ui_kit_accent_card.dart
> +                        color: Colors.white,
В этом случае черный цвет будет выглядеть следующим образом для светлой темы, поэтому решил оставить константный белый: <br>
<div>
<img width="357" alt="image" src="https://github.com/shuffle-app/shuffle_uikit/assets/101862863/d86c3bd2-f70f-4fd5-bf55-7a7832fd816d">
<img width="355" alt="image" src="https://github.com/shuffle-app/shuffle_uikit/assets/101862863/edcd5fb0-6cfb-487d-ad7c-3e0a279d6626">
<div/>

2023-09-11 14:45 UTC, romancores commented on lib/ui_kit/atoms/buttons/blurred_progress_button.dart
принимается

2023-09-12 16:48 UTC, romancores approved these changes

2023-09-12 16:49 UTC, romancores commented
@naveenpardeep could you please run app with new light theme and check how it works? check if there is need to update components/app repos within this changes

2023-09-13 06:53 UTC, naveenpardeep approved these changes

2023-09-13 12:43 UTC, merged